stages:
  - release
  - publish

variables:
  PROTOC_VERSION: "3.14.0"
  PROTOC_ZIP: protoc-${PROTOC_VERSION}-linux-x86_32.zip


default:
  image: node:latest
  before_script:
    - npm ci --cache .npm --prefer-offline
    - |
      {
        echo "@${CI_PROJECT_ROOT_NAMESPACE}:registry=${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/npm/"
        echo "${CI_API_V4_URL#https?}/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=\${CI_JOB_TOKEN}"
      } | tee -a .npmrc
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .npm/

publish-npm:
  image: node:18
  stage: publish
  variables:
    NPM_TOKEN: ${CI_JOB_TOKEN}
  before_script:
    - apt-get update
    - apt-get install -y protobuf-compiler make gettext-base
  script:
    - make init-node
    - make node
    - envsubst < package.json | tee package.json
    - echo "//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}">.npmrc
    - npm publish

  artifacts:
    paths:
      - src/*
      - lib/*
  rules:
    - if: $CI_COMMIT_BRANCH

release:
  stage: release
  script:
    - npm i
    - npm run semantic-release
  only:
    - main
    - dev


publish-python:
    image: python:3.9
    stage: publish
    before_script:
        - apt-get update
        - apt-get install -y protobuf-compiler make gettext-base
    script:
        - make init-python
        - make python
        - pip install build twine
        - export VERSION=${CI_COMMIT_TAG} && cat setup.py | envsubst > src/py/setup.py
        - cp README.md src/py/README.md
        - cp setup.cfg src/py/setup.cfg
        - cd src/py/
        - python -m build
        - TWINE_PASSWORD=${CI_JOB_TOKEN} TWINE_USERNAME=gitlab-ci-token python -m twine upload --repository-url ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi dist/*
    artifacts:
        paths:
        - src/*
        - lib/*
    rules:
        - if: $CI_COMMIT_TAG
